locale: "en-US"
title: "Jia Gu, 顾嘉"
name: "Jia Gu"
description: "Statistics"
url: "https://jia-gu.github.io"
baseurl: ""
repository: "jia-gu/jia-gu.github.io"
timezone: "America/Los_Angeles"

author:
  name: "Jia Gu"
  avatar: "/images/me.jpg"
  bio: "Email: gujia [at] zju [dot] edu [dot] cn"
  location: "Hangzhou, China"
  github: "https://github.com/jia-gu"
  googlescholar: "https://scholar.google.com/citations?hl=en&user=hlkePPcAAAAJ"

include:
  - _pages
  - files

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
  - .bundle
  - .jekyll-cache
  - .sass-cache

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo

collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publication/:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: teaching
    values:
      layout: detail
  - scope:
      path: ""
      type: publications
    values:
      layout: detail

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
